# The URL the site will be built for
base_url = "https://bakoyannis.github.io/"
title = "Thomas's Blog"
description = ""

default_language = "en"

theme = "anemone"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
build_search_index = true

taxonomies = [
    {name = "tags", feed = true}
]

[markdown]
highlight_code = true
#highlight_theme = "base16-ocean-dark"

[extra]
favicon = "/icon.ico"
default_theme = "dark"
list_pages = true
header_nav = [
  { url = "/", name_en = "/home/"},
  { url = "/blog", name_en = "/blog/"},
  { url = "/journal", name_en = "/journal/"},
  { url = "https://github.com/bakoyannis", name_en = "/github/"},
  { url = "/about", name_en = "/about/"}
]