name: Deploy to GitHub Pages

on:
 push:
  branches:
   - main

jobs:
  deploy:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 1
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@master
      env:
        env: prod
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
